@startuml
title Sonar Array Node Driver Sequence Diagram
actor User as user
participant ISonarArrayNodeDriver as interface
participant BaseSonarArrayNodeDriver as base
participant SonarArrayNodeDriver as driver
participant SonarArrayBoardPacketParser as parser

alt initialize
activate user
user -> interface++: init(Diagnostic diagnostic, Logger logger,sensor_msgs::Range[] sonars)
interface -> driver++: init(Diagnostic diagnostic,Logger logger,sensor_msgs::Range[] sonars)
driver -> base++: init(Diagnostic diagnostic, Logger, logger,sensor_msgs::Range[] sonars)
base --> driver--: diagnostic[]
driver --> interface--: diagnostic[]
interface --> user--: diagnostic[]

user -> driver++: set_comm_device(string port_name, int baud_rate)
driver -> driver: fully_initialized = true
driver --> user--: diagnostic[]
end

alt update
user -> interface++: update(double current_time, double dt)
interface -> driver++: update(double current_time, double dt)
driver -> base++: update(double current_time, doublt dt)
base --> driver--: diagnostic[]
driver -> driver: buffer = readFromSerialPort()
driver -> parser++: parsePacket(buffer)
parser --> driver--: packet
driver -> driver:  updateSonarData(packet)
driver --> interface--: diagnostic[]
interface --> user--: diagnostic[]
end

@enduml